app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

places:
    type:     rest
    resource: AppBundle\Controller\PlaceController

users:
    type:     rest
    resource: AppBundle\Controller\UserController

prices:
    type:     rest
    resource: AppBundle\Controller\Place\PriceController

themes:
    type:     rest
    resource: AppBundle\Controller\Place\ThemeController

preferences:
    type:     rest
    resource: AppBundle\Controller\User\PreferenceController

auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController

nelmio-api-doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentation
